"use client";

import Link from "next/link";
import { FormEvent, useState } from "react";
import { toast } from "sonner";

const inputClass = "h-10 w-full rounded-xl border border-border bg-background px-3 text-sm outline-none transition placeholder:text-muted-foreground focus:border-blue-300 focus:ring-4 focus:ring-blue-500/10";

export default function RegisterPage() {
  const [form, setForm] = useState({ name: "", email: "", password: "", confirmPassword: "" });
  const handleSubmit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (form.password !== form.confirmPassword) { toast.error("Passwords do not match."); return; } const response = await fetch("/api/register", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: form.name, email: form.email, password: form.password }) }); const data = await response.json(); if (!response.ok) { toast.error(data.error ?? "Registration failed"); return; } toast.success("Registration successful!"); window.location.href = "/login"; };
  return <main className="flex min-h-screen items-center justify-center bg-slate-50 px-4 py-12"><section className="w-full max-w-md rounded-2xl border border-border bg-background p-7 shadow-xl shadow-slate-950/5 sm:p-8"><p className="text-sm font-medium text-blue-600">House of EdTech</p><h1 className="mt-2 text-2xl font-semibold tracking-tight">Create your account</h1><p className="mt-2 text-sm text-muted-foreground">Start writing and collaborating with your team.</p><form onSubmit={handleSubmit} className="mt-7 space-y-4"><label htmlFor="register-name" className="grid gap-1.5 text-sm font-medium">Full name<input id="register-name" type="text" autoComplete="name" value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} placeholder="Enter your full name" required className={inputClass} /></label><label htmlFor="register-email" className="grid gap-1.5 text-sm font-medium">Email<input id="register-email" type="email" autoComplete="email" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} placeholder="name@example.com" required className={inputClass} /></label><label htmlFor="register-password" className="grid gap-1.5 text-sm font-medium">Password<input id="register-password" type="password" autoComplete="new-password" value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })} placeholder="Create a password" required className={inputClass} /></label><label htmlFor="register-confirm-password" className="grid gap-1.5 text-sm font-medium">Confirm password<input id="register-confirm-password" type="password" autoComplete="new-password" value={form.confirmPassword} onChange={(event) => setForm({ ...form, confirmPassword: event.target.value })} placeholder="Re-enter your password" required className={inputClass} /></label><button type="submit" className="mt-2 h-10 w-full rounded-xl bg-blue-600 px-4 text-sm font-semibold text-white shadow-sm transition-all hover:bg-blue-700 hover:shadow-md focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-blue-500/20 active:scale-[0.99]">Create account</button></form><p className="pt-5 text-center text-sm text-muted-foreground">Already have an account? <Link href="/login" className="font-medium text-blue-600 transition hover:text-blue-700 hover:underline">Sign in</Link></p></section></main>;
}